# Form implementation generated from reading ui file 'popup.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

class PopupWidget(object):
    def __init__(self, title, content):
        self.title = title
        self.content = content

    def setupUi(self, info_popup):
        info_popup.setObjectName("info_popup")
        info_popup.resize(900, 600)
        info_popup.setWindowFlags(QtCore.Qt.WindowType.FramelessWindowHint)
        info_popup.setAttribute(QtCore.Qt.WidgetAttribute.WA_TranslucentBackground)
        info_popup.setMinimumSize(QtCore.QSize(900, 600))
        info_popup.setMaximumSize(QtCore.QSize(900, 600))
        info_popup.setWindowTitle("")
        info_popup.setStyleSheet("\n"
"#btnClose{\n"
"background-color: rgb(0, 29, 61);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 10px solid rgb(255, 227, 90);\n"
"height: 100px;\n"
"width: 100px;\n"
"border-radius: 45px;\n"
"font-weight: bold;\n"
"}")
        self.widget = QtWidgets.QWidget(parent=info_popup)
        self.widget.setGeometry(QtCore.QRect(25, 25, 850, 550))
        self.widget.setObjectName("widget")
        self.btnClose = QtWidgets.QPushButton(parent=self.widget)
        self.btnClose.setGeometry(QtCore.QRect(750, 0, 100, 100))
        self.btnClose.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.btnClose.setFont(font)
        self.btnClose.setObjectName("btnClose")
        self.popup_frame = QtWidgets.QFrame(parent=self.widget)
        self.popup_frame.setGeometry(QtCore.QRect(25, 25, 800, 500))
        self.popup_frame.setMinimumSize(QtCore.QSize(800, 500))
        self.popup_frame.setMaximumSize(QtCore.QSize(800, 500))
        self.popup_frame.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 18px;")
        self.popup_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.popup_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.popup_frame.setObjectName("popup_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.popup_frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.popup_title = QtWidgets.QFrame(parent=self.popup_frame)
        self.popup_title.setMaximumSize(QtCore.QSize(16777215, 100))
        self.popup_title.setStyleSheet("background-color:transparent;")
        self.popup_title.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.popup_title.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.popup_title.setObjectName("popup_title")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.popup_title)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.popup_lbl_title = QtWidgets.QLabel(parent=self.popup_title)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.popup_lbl_title.setFont(font)
        self.popup_lbl_title.setStyleSheet("color: rgb(0, 29, 61);\n"
"font-weight: bold;")
        self.popup_lbl_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.popup_lbl_title.setObjectName("popup_lbl_title")
        self.verticalLayout_2.addWidget(self.popup_lbl_title)
        self.verticalLayout.addWidget(self.popup_title)
        self.popup_content = QtWidgets.QFrame(parent=self.popup_frame)
        self.popup_content.setStyleSheet("background-color: transparent;")
        self.popup_content.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.popup_content.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.popup_content.setObjectName("popup_content")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.popup_content)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.popup_lbl_content = QtWidgets.QLabel(parent=self.popup_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.popup_lbl_content.sizePolicy().hasHeightForWidth())
        self.popup_lbl_content.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.popup_lbl_content.setFont(font)
        self.popup_lbl_content.setStyleSheet("color: rgb(0, 29, 61);\n"
"margin: 0px 150px;\n"
"font-weight: bold;")
        self.popup_lbl_content.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.popup_lbl_content.setWordWrap(True)
        self.popup_lbl_content.setObjectName("popup_lbl_content")
        self.verticalLayout_3.addWidget(self.popup_lbl_content)
        self.verticalLayout.addWidget(self.popup_content)
        self.popup_frame.raise_()
        self.btnClose.raise_()

        self.retranslateUi(info_popup)
        QtCore.QMetaObject.connectSlotsByName(info_popup)


    def retranslateUi(self, info_popup):
        _translate = QtCore.QCoreApplication.translate
        self.btnClose.setText(_translate("info_popup", "X"))
        self.popup_lbl_title.setText(_translate("info_popup", self.title))
        self.popup_lbl_content.setText(_translate("info_popup", self.content))
